version: '3.9'
services:
 server:
     build:
      context: ./server
      dockerfile: Dockerfile
     image: server-image:v1.0
     container_name: express-backend 
     ports:
      - "5000:5000"
     env_file: ./.env 
     environment:
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
     depends_on:
      - mongodb
     networks:
      - backend_network  
      - frontend_network  
     
 client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-image:v1.0  
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - frontend_network
      

 mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    ports:
      - "27017:27017"
    networks:
      - backend_network   
# volumes:
networks:
  backend_network:
  frontend_network: