version: '3.9'
services:
 server:
     build:
      context: ./server
      dockerfile: Dockerfile
     image: server-image:v1.0
     container_name: express-backend 
     ports:
      - "5000:5000"
     env_file: ./.env 
     environment:
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
     depends_on:
      - mongodb
     
 client:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-image:v1.0  
    container_name: react-frontend
    ports:
      - "5000:5000"
    depends_on:
      - server

 mongodb:
volumes:
networks: