version: '3.9'
services:
 server:
     build:
      context: ./server
      dockerfile: Dockerfile
     image: server-image:v1.0
     container_name: express-backend 
     
 client:
 mongodb:
volumes:
networks: